version: "3"
services:
  invidious:
    build: .
    ports:
      - "3000:3000"
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: railway
          user: postgres
          password: JAfMPuKmusTsVuKNPctJNddgWswggzMB
          host: postgres.railway.internal
          port: 5432
        check_tables: true
        hmac_key: "CHANGE_ME"
